'use server';

/**
 * @fileOverview A mock service to simulate a lipstick product database.
 */

export type LipstickProduct = {
  id: number;
  brand: string;
  productName: string;
  hex: string;
  finish: 'Matte' | 'Satin' | 'Glossy' | 'Creme' | 'Liquid';
  buyLink: string;
};

// Mock database of lipstick products
const lipstickDatabase: LipstickProduct[] = [
  // Existing
  { id: 1, brand: 'MAC Cosmetics', productName: 'Retro Matte Lipstick in Ruby Woo', hex: '#C01A29', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 2, brand: 'Fenty Beauty', productName: 'Stunna Lip Paint in Uncensored', hex: '#A80C14', finish: 'Liquid', buyLink: 'https://fentybeauty.com' },
  { id: 3, brand: 'NARS', productName: 'Audacious Lipstick in Rita', hex: '#D62139', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 4, brand: 'Charlotte Tilbury', productName: 'Matte Revolution Lipstick in Pillow Talk', hex: '#AB786E', finish: 'Matte', buyLink: 'https://www.charlottetilbury.com' },
  { id: 5, brand: 'Dior', productName: 'Rouge Dior Lipstick in 999', hex: '#D01F28', finish: 'Satin', buyLink: 'https://www.dior.com' },
  { id: 6, brand: 'Yves Saint Laurent', productName: 'Rouge Pur Couture in Le Rouge (01)', hex: '#D82C35', finish: 'Satin', buyLink: 'https://www.yslbeautyus.com' },
  { id: 7, brand: 'Pat McGrath Labs', productName: 'MatteTrance Lipstick in Elson', hex: '#B8242A', finish: 'Matte', buyLink: 'https://www.patmcgrath.com' },
  { id: 8, brand: 'Rare Beauty', productName: 'Lip Soufflé Matte Lip Cream in Inspire', hex: '#D04A4A', finish: 'Matte', buyLink: 'https://www.rarebeauty.com' },
  { id: 9, brand: 'Clinique', productName: 'Almost Lipstick in Black Honey', hex: '#5B3439', finish: 'Glossy', buyLink: 'https://www.clinique.com' },
  { id: 10, brand: 'Glossier', productName: 'Generation G in Zip', hex: '#E5594F', finish: 'Matte', buyLink: 'https://www.glossier.com' },
  
  // Expanded Reds
  { id: 11, brand: 'Maybelline', productName: 'SuperStay Matte Ink in Pioneer', hex: '#B51E24', finish: 'Liquid', buyLink: 'https://www.maybelline.com' },
  { id: 12, brand: 'L\'Oréal Paris', productName: 'Colour Riche in Blake\'s Red', hex: '#C61D23', finish: 'Creme', buyLink: 'https://www.lorealparisusa.com' },
  { id: 13, brand: 'MAC Cosmetics', productName: 'Lipstick in Russian Red', hex: '#A71C1E', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 14, brand: 'Revlon', productName: 'Super Lustrous Lipstick in Fire & Ice', hex: '#E04443', finish: 'Creme', buyLink: 'https://www.revlon.com' },
  { id: 15, brand: 'Armani Beauty', productName: 'Lip Maestro in 400', hex: '#9E1C21', finish: 'Liquid', buyLink: 'https://www.giorgioarmanibeauty-usa.com' },
  { id: 16, brand: 'Givenchy', productName: 'Le Rouge Deep Velvet in 37', hex: '#8C1B1F', finish: 'Matte', buyLink: 'https://www.givenchybeauty.com' },
  { id: 17, brand: 'Chanel', productName: 'Rouge Allure in Pirate', hex: '#AF1923', finish: 'Satin', buyLink: 'https://www.chanel.com' },
  { id: 18, brand: 'Tom Ford', productName: 'Lip Color in Cherry Lush', hex: '#C72C41', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 19, brand: 'Huda Beauty', productName: 'Power Bullet Matte in El Cinco De Mayo', hex: '#D7383D', finish: 'Matte', buyLink: 'https://hudabeauty.com' },
  { id: 20, brand: 'Sephora Collection', productName: 'Cream Lip Stain in 01 Always Red', hex: '#B3131A', finish: 'Liquid', buyLink: 'https://www.sephora.com' },
  
  // Expanded Pinks
  { id: 21, brand: 'NARS', productName: 'Audacious Lipstick in Schiap', hex: '#E73980', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 22, brand: 'MAC Cosmetics', productName: 'Lipstick in Candy Yum-Yum', hex: '#EE659E', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 23, brand: 'Charlotte Tilbury', productName: 'Matte Revolution in The Queen', hex: '#D83E58', finish: 'Matte', buyLink: 'https://www.charlottetilbury.com' },
  { id: 24, brand: 'Fenty Beauty', productName: 'Mattemoiselle in Flamingo Acid', hex: '#F0628D', finish: 'Matte', buyLink: 'https://fentybeauty.com' },
  { id: 25, brand: 'Too Faced', productName: 'Melted Matte in 1998', hex: '#D96A74', finish: 'Liquid', buyLink: 'https://www.toofaced.com' },
  { id: 26, brand: 'Bobbi Brown', productName: 'Crushed Lip Color in Babe', hex: '#C76A6F', finish: 'Satin', buyLink: 'https://www.bobbibrowncosmetics.com' },
  { id: 27, brand: 'Urban Decay', productName: 'Vice Lipstick in Backtalk', hex: '#AC6A6A', finish: 'Creme', buyLink: 'https://www.urbandecay.com' },
  { id: 28, brand: 'Kylie Cosmetics', productName: 'Matte Lip Kit in Candy K', hex: '#C18379', finish: 'Liquid', buyLink: 'https://kyliecosmetics.com' },
  { id: 29, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Doll Parts', hex: '#D77B8A', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 30, brand: 'ColourPop', productName: 'Ultra Matte Lip in Tulle', hex: '#A05C5E', finish: 'Liquid', buyLink: 'https://colourpop.com' },

  // Expanded Nudes & Browns
  { id: 31, brand: 'MAC Cosmetics', productName: 'Lipstick in Velvet Teddy', hex: '#B8877A', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 32, brand: 'Charlotte Tilbury', productName: 'Matte Revolution in Pillow Talk Medium', hex: '#A76964', finish: 'Matte', buyLink: 'https://www.charlottetilbury.com' },
  { id: 33, brand: 'Fenty Beauty', productName: 'Gloss Bomb in Fenty Glow', hex: '#B08375', finish: 'Glossy', buyLink: 'https://fentybeauty.com' },
  { id: 34, brand: 'Anastasia Beverly Hills', productName: 'Matte Lipstick in Stripped', hex: '#D2A895', finish: 'Matte', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 35, brand: 'Huda Beauty', productName: 'Liquid Matte in Bombshell', hex: '#C88D7F', finish: 'Liquid', buyLink: 'https://hudabeauty.com' },
  { id: 36, brand: 'Maybelline', productName: 'SuperStay Matte Ink in Loyalist', hex: '#C99A8E', finish: 'Liquid', buyLink: 'https://www.maybelline.com' },
  { id: 37, brand: 'NARS', productName: 'Powermatte Lip Pigment in American Woman', hex: '#B36A6A', finish: 'Liquid', buyLink: 'https://www.narscosmetics.com' },
  { id: 38, brand: 'MAC Cosmetics', productName: 'Lipstick in Taupe', hex: '#A16A5A', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 39, brand: 'ColourPop', productName: 'Ultra Blotted Lip in Zuma', hex: '#C28E82', finish: 'Liquid', buyLink: 'https://colourpop.com' },
  { id: 40, brand: 'Lime Crime', productName: 'Velvetines in Salem', hex: '#5E382E', finish: 'Liquid', buyLink: 'https://limecrime.com' },
  
  // Expanded Berries & Purples
  { id: 41, brand: 'MAC Cosmetics', productName: 'Lipstick in Heroine', hex: '#8B428A', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 42, brand: 'NARS', productName: 'Audacious Lipstick in Liv', hex: '#633A42', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 43, brand: 'Revlon', productName: 'Super Lustrous Lipstick in Berry Haute', hex: '#A34A6E', finish: 'Creme', buyLink: 'https://www.revlon.com' },
  { id: 44, brand: 'Fenty Beauty', productName: 'Mattemoiselle in Violet Fury', hex: '#7D3F99', finish: 'Matte', buyLink: 'https://fentybeauty.com' },
  { id: 45, brand: 'Pat McGrath Labs', productName: 'MatteTrance in Deep Orchid', hex: '#8E3A65', finish: 'Matte', buyLink: 'https://www.patmcgrath.com' },
  { id: 46, brand: 'Urban Decay', productName: 'Vice Lipstick in Pandemonium', hex: '#703D8A', finish: 'Matte', buyLink: 'https://www.urbandecay.com' },
  { id: 47, brand: 'Tom Ford', productName: 'Lip Color in Bruised Plum', hex: '#753A4A', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 48, brand: 'MAC Cosmetics', productName: 'Lipstick in Diva', hex: '#7A2A2F', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 49, brand: 'Bite Beauty', productName: 'Amuse Bouche in Jam', hex: '#823751', finish: 'Satin', buyLink: 'https://www.bitebeauty.com' },
  { id: 50, brand: 'Huda Beauty', productName: 'Power Bullet Matte in Ladies Night', hex: '#783348', finish: 'Matte', buyLink: 'https://hudabeauty.com' },

  // Add 450 more shades
  // ... Pinks
  { id: 51, brand: 'Dior', productName: 'Addict Lip Glow in 001 Pink', hex: '#FBCFE0', finish: 'Glossy', buyLink: 'https://www.dior.com' },
  { id: 52, brand: 'Glossier', productName: 'Cloud Paint in Puff', hex: '#E8A6B1', finish: 'Creme', buyLink: 'https://www.glossier.com' },
  { id: 53, brand: 'Benefit Cosmetics', productName: 'Posietint', hex: '#ED83A8', finish: 'Liquid', buyLink: 'https://www.benefitcosmetics.com' },
  { id: 54, brand: 'Tarte', productName: 'Maracuja Juicy Lip in Rose', hex: '#DDA8A7', finish: 'Glossy', buyLink: 'https://tartecosmetics.com' },
  { id: 55, brand: 'MAC Cosmetics', productName: 'Lipstick in Snob', hex: '#E0A3B5', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 56, brand: 'Yves Saint Laurent', productName: 'Rouge Volupté Shine in 49 Rose Saint Germain', hex: '#D86D8B', finish: 'Glossy', buyLink: 'https://www.yslbeautyus.com' },
  { id: 57, brand: 'L\'Oréal Paris', productName: 'Colour Riche in Fairest Nude', hex: '#E5C2B4', finish: 'Creme', buyLink: 'https://www.lorealparisusa.com' },
  { id: 58, brand: 'Maybelline', productName: 'Color Sensational in Pink Please', hex: '#EBAEC6', finish: 'Creme', buyLink: 'https://www.maybelline.com' },
  { id: 59, brand: 'Fenty Beauty', productName: 'Gloss Bomb in Fu$$y', hex: '#D9A1A0', finish: 'Glossy', buyLink: 'https://fentybeauty.com' },
  { id: 60, brand: 'Kylie Cosmetics', productName: 'High Gloss in Klear', hex: '#FDFDFD', finish: 'Glossy', buyLink: 'https://kyliecosmetics.com' },
  // ... Corals
  { id: 61, brand: 'MAC Cosmetics', productName: 'Lipstick in Vegas Volt', hex: '#F08068', finish: 'Creme', buyLink: 'https://www.maccosmetics.com' },
  { id: 62, brand: 'NARS', productName: 'Lipstick in Orgasm', hex: '#F2A098', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 63, brand: 'Too Faced', productName: 'Peach Kiss in Got Peach?', hex: '#F38D77', finish: 'Matte', buyLink: 'https://www.toofaced.com' },
  { id: 64, brand: 'ColourPop', productName: 'Ultra Matte Lip in Speed Up', hex: '#EE765B', finish: 'Liquid', buyLink: 'https://colourpop.com' },
  { id: 65, brand: 'Clinique', productName: 'Chubby Stick in Mighty Mimosa', hex: '#F2A99A', finish: 'Glossy', buyLink: 'https://www.clinique.com' },
  { id: 66, brand: 'Revlon', productName: 'Super Lustrous in Coral Berry', hex: '#E86F68', finish: 'Creme', buyLink: 'https://www.revlon.com' },
  { id: 67, brand: 'Tom Ford', productName: 'Lip Color in True Coral', hex: '#E95D54', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 68, brand: 'Bobbi Brown', productName: 'Luxe Lip Color in Sunset Orange', hex: '#ED6944', finish: 'Satin', buyLink: 'https://www.bobbibrowncosmetics.com' },
  { id: 69, brand: 'Shiseido', productName: 'VisionAiry Gel Lipstick in Ginza Red', hex: '#E64C4C', finish: 'Satin', buyLink: 'https://www.shiseido.com' },
  { id: 70, brand: 'Gucci', productName: 'Rouge à Lèvres Voile in Agatha Orange', hex: '#E37A5E', finish: 'Glossy', buyLink: 'https://www.gucci.com' },
  // ... Oranges
  { id: 71, brand: 'MAC Cosmetics', productName: 'Lipstick in Morange', hex: '#F5783A', finish: 'Creme', buyLink: 'https://www.maccosmetics.com' },
  { id: 72, brand: 'Fenty Beauty', productName: 'Mattemoiselle in Saw-C', hex: '#F3732F', finish: 'Matte', buyLink: 'https://fentybeauty.com' },
  { id: 73, brand: 'Huda Beauty', productName: 'Power Bullet in Promotion Day', hex: '#E76135', finish: 'Matte', buyLink: 'https://hudabeauty.com' },
  { id: 74, brand: 'Maybelline', productName: 'Color Sensational in Electric Orange', hex: '#F88031', finish: 'Creme', buyLink: 'https://www.maybelline.com' },
  { id: 75, brand: 'Lime Crime', productName: 'Velvetines in Psycho', hex: '#FF5C00', finish: 'Liquid', buyLink: 'https://limecrime.com' },
  { id: 76, brand: 'Pat McGrath Labs', productName: 'BlitzTrance in Flesh Fatale', hex: '#E26D49', finish: 'Satin', buyLink: 'https://www.patmcgrath.com' },
  { id: 77, brand: 'NARS', productName: 'Heatwave', hex: '#FF4D00', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 78, brand: 'Dior', productName: 'Rouge Dior Ultra Care Liquid in 707 Bliss', hex: '#E47B59', finish: 'Liquid', buyLink: 'https://www.dior.com' },
  { id: 79, brand: 'Sephora Collection', productName: 'Lipstories in 31 Golden Gate', hex: '#F48E54', finish: 'Creme', buyLink: 'https://www.sephora.com' },
  { id: 80, brand: 'Anastasia Beverly Hills', productName: 'Liquid Lipstick in Spicy', hex: '#E06538', finish: 'Liquid', buyLink: 'https://www.anastasiabeverlyhills.com' },
  // ... Deep Browns
  { id: 81, brand: 'MAC Cosmetics', productName: 'Lipstick in Antique Velvet', hex: '#583636', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 82, brand: 'NARS', productName: 'Audacious in Deborah', hex: '#6E4840', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 83, brand: 'Fenty Beauty', productName: 'Stunna Lip Paint in Unveil', hex: '#735041', finish: 'Liquid', buyLink: 'https://fentybeauty.com' },
  { id: 84, brand: 'Kylie Cosmetics', productName: 'Matte Lip Kit in True Brown K', hex: '#4B332E', finish: 'Liquid', buyLink: 'https://kyliecosmetics.com' },
  { id: 85, brand: 'ColourPop', productName: 'Ultra Matte Lip in Limbo', hex: '#6B4037', finish: 'Liquid', buyLink: 'https://colourpop.com' },
  { id: 86, brand: 'Huda Beauty', productName: 'Liquid Matte in Vixen', hex: '#60393B', finish: 'Liquid', buyLink: 'https://hudabeauty.com' },
  { id: 87, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Dominatrix', hex: '#4E342E', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 88, brand: 'Maybelline', productName: 'SuperStay Matte Ink in Fighter', hex: '#8C523A', finish: 'Liquid', buyLink: 'https://www.maybelline.com' },
  { id: 89, brand: 'Bobbi Brown', productName: 'Crushed Lip Color in Dark Chocolate', hex: '#5C3D38', finish: 'Satin', buyLink: 'https://www.bobbibrowncosmetics.com' },
  { id: 90, brand: 'Pat McGrath Labs', productName: 'LuxeTrance in Exxotica', hex: '#78473B', finish: 'Creme', buyLink: 'https://www.patmcgrath.com' },
  // ... Vamps & Burgundies
  { id: 91, brand: 'Chanel', productName: 'Rouge Allure in Rouge Noir', hex: '#51272D', finish: 'Satin', buyLink: 'https://www.chanel.com' },
  { id: 92, brand: 'MAC Cosmetics', productName: 'Lipstick in Sin', hex: '#63262A', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 93, brand: 'Tom Ford', productName: 'Lip Color in Black Dahlia', hex: '#501F29', finish: 'Matte', buyLink: 'https://www.tomford.com' },
  { id: 94, brand: 'Revlon', productName: 'Super Lustrous in Black Cherry', hex: '#612E3B', finish: 'Creme', buyLink: 'https://www.revlon.com' },
  { id: 95, brand: 'NARS', productName: 'Audacious Lipstick in Bette', hex: '#732D3F', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 96, brand: 'Dior', productName: 'Rouge Dior in 964 Ambitious Matte', hex: '#7A3247', finish: 'Matte', buyLink: 'https://www.dior.com' },
  { id: 97, brand: 'Wet n Wild', productName: 'MegaLast Lip Color in Cherry Bomb', hex: '#6F2B39', finish: 'Matte', buyLink: 'https://www.wetnwildbeauty.com' },
  { id: 98, brand: 'Armani Beauty', productName: 'Lip Maestro in 201', hex: '#752A2A', finish: 'Liquid', buyLink: 'https://www.giorgioarmanibeauty-usa.com' },
  { id: 99, brand: 'Givenchy', productName: 'Le Rouge in 333 L\'Interdit', hex: '#841E26', finish: 'Satin', buyLink: 'https://www.givenchybeauty.com' },
  { id: 100, brand: 'Charlotte Tilbury', productName: 'Matte Revolution in Glastonberry', hex: '#693244', finish: 'Matte', buyLink: 'https://www.charlottetilbury.com' },
  // ... Unconventional Colors
  { id: 101, brand: 'Fenty Beauty', productName: 'Mattemoiselle in Ya Dig?!', hex: '#2E4A52', finish: 'Matte', buyLink: 'https://fentybeauty.com' },
  { id: 102, brand: 'KVD Beauty', productName: 'Everlasting Liquid Lipstick in Witches', hex: '#1A1A1A', finish: 'Liquid', buyLink: 'https://www.kvdveganbeauty.com' },
  { id: 103, brand: 'NYX', productName: 'Liquid Suede in Stone Fox', hex: '#4A4A4A', finish: 'Liquid', buyLink: 'https://www.nyxcosmetics.com' },
  { id: 104, brand: 'MAC Cosmetics', productName: 'Lipstick in Frosting', hex: '#F0F0F0', finish: 'Creme', buyLink: 'https://www.maccosmetics.com' },
  { id: 105, brand: 'Lime Crime', productName: 'Velvetines in Cement', hex: '#8B8C89', finish: 'Liquid', buyLink: 'https://limecrime.com' },
  { id: 106, brand: 'Urban Decay', productName: 'Vice Lipstick in Perversion', hex: '#101010', finish: 'Creme', buyLink: 'https://www.urbandecay.com' },
  { id: 107, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Breakfast at Tiffany\'s', hex: '#5DD4C6', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 108, brand: 'Fenty Beauty', productName: 'Mattemoiselle in Clapback', hex: '#163B4C', finish: 'Matte', buyLink: 'https://fentybeauty.com' },
  { id: 109, brand: 'Make Up For Ever', productName: 'Artist Rouge in C603', hex: '#314E7C', finish: 'Creme', buyLink: 'https://www.makeupforever.com' },
  { id: 110, brand: 'Anastasia Beverly Hills', productName: 'Matte Lipstick in Cobalt', hex: '#0047AB', finish: 'Matte', buyLink: 'https://www.anastasiabeverlyhills.com' },
  // More...
  { id: 111, brand: 'MAC Cosmetics', productName: 'Lipstick in Mehr', hex: '#C27E7F', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 112, brand: 'MAC Cosmetics', productName: 'Lipstick in Twig', hex: '#B57E74', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 113, brand: 'MAC Cosmetics', productName: 'Lipstick in Kinda Sexy', hex: '#E2A188', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 114, brand: 'MAC Cosmetics', productName: 'Lipstick in Honeylove', hex: '#D8A98F', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 115, brand: 'MAC Cosmetics', productName: 'Lipstick in Brave', hex: '#CE9093', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 116, brand: 'MAC Cosmetics', productName: 'Lipstick in Spirit', hex: '#A87563', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 117, brand: 'MAC Cosmetics', productName: 'Lipstick in Whirl', hex: '#A06B62', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 118, brand: 'MAC Cosmetics', productName: 'Lipstick in Mocha', hex: '#C18868', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 119, brand: 'MAC Cosmetics', productName: 'Lipstick in Chili', hex: '#B54932', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 120, brand: 'MAC Cosmetics', productName: 'Lipstick in Lady Danger', hex: '#E54C2C', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 121, brand: 'MAC Cosmetics', productName: 'Lipstick in All Fired Up', hex: '#D94B69', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 122, brand: 'MAC Cosmetics', productName: 'Lipstick in Flat Out Fabulous', hex: '#C24D8A', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 123, brand: 'MAC Cosmetics', productName: 'Lipstick in Rebel', hex: '#87395E', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 124, brand: 'MAC Cosmetics', productName: 'Lipstick in Cyber', hex: '#482D46', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 125, brand: 'MAC Cosmetics', productName: 'Lipstick in Media', hex: '#7A333F', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 126, brand: 'NARS', productName: 'Powermatte Lip Pigment in Starwoman', hex: '#A61A21', finish: 'Liquid', buyLink: 'https://www.narscosmetics.com' },
  { id: 127, brand: 'NARS', productName: 'Powermatte Lip Pigment in Don\'t Stop', hex: '#B61F24', finish: 'Liquid', buyLink: 'https://www.narscosmetics.com' },
  { id: 128, brand: 'NARS', productName: 'Powermatte Lip Pigment in Light My Fire', hex: '#E25431', finish: 'Liquid', buyLink: 'https://www.narscosmetics.com' },
  { id: 129, brand: 'NARS', productName: 'Powermatte Lip Pigment in Slow Ride', hex: '#B26956', finish: 'Liquid', buyLink: 'https://www.narscosmetics.com' },
  { id: 130, brand: 'NARS', productName: 'Powermatte Lip Pigment in Save the Queen', hex: '#A86C81', finish: 'Liquid', buyLink: 'https://www.narscosmetics.com' },
  { id: 131, brand: 'NARS', productName: 'Audacious Lipstick in Anita', hex: '#D2958D', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 132, brand: 'NARS', productName: 'Audacious Lipstick in Barbara', hex: '#CB9080', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 133, brand: 'NARS', productName: 'Audacious Lipstick in Anna', hex: '#C17D91', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 134, brand: 'NARS', productName: 'Velvet Matte Lip Pencil in Cruella', hex: '#9B2C30', finish: 'Matte', buyLink: 'https://www.narscosmetics.com' },
  { id: 135, brand: 'NARS', productName: 'Velvet Matte Lip Pencil in Dragon Girl', hex: '#D03144', finish: 'Matte', buyLink: 'https://www.narscosmetics.com' },
  { id: 136, brand: 'Charlotte Tilbury', productName: 'Matte Revolution in Very Victoria', hex: '#A87A6D', finish: 'Matte', buyLink: 'https://www.charlottetilbury.com' },
  { id: 137, brand: 'Charlotte Tilbury', productName: 'K.I.S.S.I.N.G. in Bitch Perfect', hex: '#E4A999', finish: 'Satin', buyLink: 'https://www.charlottetilbury.com' },
  { id: 138, brand: 'Charlotte Tilbury', productName: 'Hot Lips in Kim K.W.', hex: '#E4B6A6', finish: 'Creme', buyLink: 'https://www.charlottetilbury.com' },
  { id: 139, brand: 'Charlotte Tilbury', productName: 'Hot Lips 2 in Glowing Jen', hex: '#D77E6A', finish: 'Satin', buyLink: 'https://www.charlottetilbury.com' },
  { id: 140, brand: 'Charlotte Tilbury', productName: 'Superstar Lips in Pillow Talk', hex: '#C3877F', finish: 'Glossy', buyLink: 'https://www.charlottetilbury.com' },
  { id: 141, brand: 'Tom Ford', productName: 'Lip Color in Indian Rose', hex: '#C47E7A', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 142, brand: 'Tom Ford', productName: 'Lip Color in Casablanca', hex: '#A86565', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 143, brand: 'Tom Ford', productName: 'Lip Color in Spanish Pink', hex: '#E3A39A', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 144, brand: 'Tom Ford', productName: 'Lip Color Matte in Flame', hex: '#E15A2E', finish: 'Matte', buyLink: 'https://www.tomford.com' },
  { id: 145, brand: 'Tom Ford', productName: 'Lip Color Matte in Pussycat', hex: '#B86B77', finish: 'Matte', buyLink: 'https://www.tomford.com' },
  { id: 146, brand: 'Pat McGrath Labs', productName: 'MatteTrance in Omi', hex: '#B76E6F', finish: 'Matte', buyLink: 'https://www.patmcgrath.com' },
  { id: 147, brand: 'Pat McGrath Labs', productName: 'MatteTrance in 1995', hex: '#C18678', finish: 'Matte', buyLink: 'https://www.patmcgrath.com' },
  { id: 148, brand: 'Pat McGrath Labs', productName: 'MatteTrance in Flesh 3', hex: '#8C4B48', finish: 'Matte', buyLink: 'https://www.patmcgrath.com' },
  { id: 149, brand: 'Pat McGrath Labs', productName: 'LuxeTrance in LaBeija', hex: '#D59483', finish: 'Creme', buyLink: 'https://www.patmcgrath.com' },
  { id: 150, brand: 'Pat McGrath Labs', productName: 'BlitzTrance in Fuchsia Perfect', hex: '#D4377A', finish: 'Satin', buyLink: 'https://www.patmcgrath.com' },
  { id: 151, brand: 'Fenty Beauty', productName: 'Stunna Lip Paint in Unbutton', hex: '#DAB3A1', finish: 'Liquid', buyLink: 'https://fentybeauty.com' },
  { id: 152, brand: 'Fenty Beauty', productName: 'Stunna Lip Paint in Uncuffed', hex: '#C18386', finish: 'Liquid', buyLink: 'https://fentybeauty.com' },
  { id: 153, brand: 'Fenty Beauty', productName: 'Gloss Bomb in Diamond Milk', hex: '#F0E5E0', finish: 'Glossy', buyLink: 'https://fentybeauty.com' },
  { id: 154, brand: 'Fenty Beauty', productName: 'Mattemoiselle in S1ngle', hex: '#C9917F', finish: 'Matte', buyLink: 'https://fentybeauty.com' },
  { id: 155, brand: 'Fenty Beauty', productName: 'Mattemoiselle in Griselda', hex: '#63252E', finish: 'Matte', buyLink: 'https://fentybeauty.com' },
  { id: 156, brand: 'Huda Beauty', productName: 'Liquid Matte in Trendsetter', hex: '#A86D58', finish: 'Liquid', buyLink: 'https://hudabeauty.com' },
  { id: 157, brand: 'Huda Beauty', productName: 'Liquid Matte in Trophy Wife', hex: '#B95D75', finish: 'Liquid', buyLink: 'https://hudabeauty.com' },
  { id: 158, brand: 'Huda Beauty', productName: 'Power Bullet Matte in Interview', hex: '#C98574', finish: 'Matte', buyLink: 'https://hudabeauty.com' },
  { id: 159, brand: 'Huda Beauty', productName: 'Power Bullet Matte in Wedding Day', hex: '#D6A49A', finish: 'Matte', buyLink: 'https://hudabeauty.com' },
  { id: 160, brand: 'Huda Beauty', productName: 'Demi Matte in Feminist', hex: '#CB7464', finish: 'Satin', buyLink: 'https://hudabeauty.com' },
  { id: 161, brand: 'Anastasia Beverly Hills', productName: 'Liquid Lipstick in Pure Hollywood', hex: '#E1B8A8', finish: 'Liquid', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 162, brand: 'Anastasia Beverly Hills', productName: 'Liquid Lipstick in Ashton', hex: '#B77759', finish: 'Liquid', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 163, brand: 'Anastasia Beverly Hills', productName: 'Liquid Lipstick in Dusty Rose', hex: '#C38989', finish: 'Liquid', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 164, brand: 'Anastasia Beverly Hills', productName: 'Matte Lipstick in Dead Roses', hex: '#9E646C', finish: 'Matte', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 165, brand: 'Anastasia Beverly Hills', productName: 'Matte Lipstick in Staunch', hex: '#D19C7F', finish: 'Matte', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 166, brand: 'Kylie Cosmetics', productName: 'Matte Lip Kit in Exposed', hex: '#C58F78', finish: 'Liquid', buyLink: 'https://kyliecosmetics.com' },
  { id: 167, brand: 'Kylie Cosmetics', productName: 'Matte Lip Kit in Dolce K', hex: '#B6826C', finish: 'Liquid', buyLink: 'https://kyliecosmetics.com' },
  { id: 168, brand: 'Kylie Cosmetics', productName: 'Matte Lip Kit in Koko K', hex: '#E2A9A8', finish: 'Liquid', buyLink: 'https://kyliecosmetics.com' },
  { id: 169, brand: 'Kylie Cosmetics', productName: 'Velvet Lip Kit in Posie K', hex: '#B96A7F', finish: 'Satin', buyLink: 'https://kyliecosmetics.com' },
  { id: 170, brand: 'Kylie Cosmetics', productName: 'Crème Lipstick in Crème Brûlée', hex: '#D79E90', finish: 'Creme', buyLink: 'https://kyliecosmetics.com' },
  { id: 171, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Celebrity Skin', hex: '#C89C82', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 172, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Gemini', hex: '#B67970', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 173, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Androgyny', hex: '#A3606A', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 174, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Redrum', hex: '#C11F24', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 175, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Unicorn Blood', hex: '#772A24', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 176, brand: 'ColourPop', productName: 'Ultra Matte Lip in Beeper', hex: '#B87E6E', finish: 'Liquid', buyLink: 'https://colourpop.com' },
  { id: 177, brand: 'ColourPop', productName: 'Ultra Matte Lip in Clueless', hex: '#D4A3A2', finish: 'Liquid', buyLink: 'https://colourpop.com' },
  { id: 178, brand: 'ColourPop', productName: 'Ultra Satin Lip in Frick N Frack', hex: '#9D5859', finish: 'Satin', buyLink: 'https://colourpop.com' },
  { id: 179, brand: 'ColourPop', productName: 'Lux Lipstick in Lay Over', hex: '#A0614F', finish: 'Creme', buyLink: 'https://colourpop.com' },
  { id: 180, brand: 'ColourPop', productName: 'Just a Tint in City of Stars', hex: '#C17B69', finish: 'Glossy', buyLink: 'https://colourpop.com' },
  { id: 181, brand: 'Maybelline', productName: 'SuperStay Matte Ink in Seductress', hex: '#C1887C', finish: 'Liquid', buyLink: 'https://www.maybelline.com' },
  { id: 182, brand: 'Maybelline', productName: 'SuperStay Matte Ink in Lover', hex: '#C47E84', finish: 'Liquid', buyLink: 'https://www.maybelline.com' },
  { id: 183, brand: 'Maybelline', productName: 'Color Sensational in Totally Toffee', hex: '#B17C64', finish: 'Creme', buyLink: 'https://www.maybelline.com' },
  { id: 184, brand: 'Maybelline', productName: 'Color Sensational in Nude Lust', hex: '#E5BFB0', finish: 'Creme', buyLink: 'https://www.maybelline.com' },
  { id: 185, brand: 'Maybelline', productName: 'Made For All in Mauve For Me', hex: '#B47474', finish: 'Satin', buyLink: 'https://www.maybelline.com' },
  { id: 186, brand: 'L\'Oréal Paris', productName: 'Colour Riche in Shining Peach', hex: '#E9977C', finish: 'Creme', buyLink: 'https://www.lorealparisusa.com' },
  { id: 187, brand: 'L\'Oréal Paris', productName: 'Rouge Signature in I Rule', hex: '#CB8589', finish: 'Liquid', buyLink: 'https://www.lorealparisusa.com' },
  { id: 188, brand: 'L\'Oréal Paris', productName: 'Infallible Pro-Matte in Les Macarons', hex: '#D38A7F', finish: 'Matte', buyLink: 'https://www.lorealparisusa.com' },
  { id: 189, brand: 'L\'Oréal Paris', productName: 'Colour Riche Shine in Varnished Rosewood', hex: '#B57469', finish: 'Glossy', buyLink: 'https://www.lorealparisusa.com' },
  { id: 190, brand: 'L\'Oréal Paris', productName: 'Colour Riche in Brazil Nut', hex: '#875143', finish: 'Creme', buyLink: 'https://www.lorealparisusa.com' },
  { id: 191, brand: 'Revlon', productName: 'Ultra HD Matte in Seduction', hex: '#D29B87', finish: 'Matte', buyLink: 'https://www.revlon.com' },
  { id: 192, brand: 'Revlon', productName: 'Super Lustrous in Rum Raisin', hex: '#87514B', finish: 'Creme', buyLink: 'https://www.revlon.com' },
  { id: 193, brand: 'Revlon', productName: 'ColorStay Ultimate Suede in Finale', hex: '#A3544D', finish: 'Satin', buyLink: 'https://www.revlon.com' },
  { id: 194, brand: 'Revlon', productName: 'Kiss Cushion Lip Tint in Naughty Mauve', hex: '#B87274', finish: 'Glossy', buyLink: 'https://www.revlon.com' },
  { id: 195, brand: 'Revlon', productName: 'Super Lustrous in Pink in the Afternoon', hex: '#DD9993', finish: 'Creme', buyLink: 'https://www.revlon.com' },
  { id: 196, brand: 'Urban Decay', productName: 'Vice Lipstick in Naked', hex: '#D1A392', finish: 'Creme', buyLink: 'https://www.urbandecay.com' },
  { id: 197, brand: 'Urban Decay', productName: 'Vice Lipstick in Manic', hex: '#A95856', finish: 'Creme', buyLink: 'https://www.urbandecay.com' },
  { id: 198, brand: 'Urban Decay', productName: 'Vice Lipstick in 1993', hex: '#946755', finish: 'Matte', buyLink: 'https://www.urbandecay.com' },
  { id: 199, brand: 'Urban Decay', productName: 'Comfort Matte in Safe Word', hex: '#B37866', finish: 'Matte', buyLink: 'https://www.urbandecay.com' },
  { id: 200, brand: 'Urban Decay', productName: 'Hi-Fi Shine Lipgloss in SPL', hex: '#E2A9A3', finish: 'Glossy', buyLink: 'https://www.urbandecay.com' },
  // Adding 300 more...
  { id: 201, brand: 'Dior', productName: 'Addict Lacquer Stick in 550 Tease', hex: '#D38089', finish: 'Glossy', buyLink: 'https://www.dior.com' },
  { id: 202, brand: 'Chanel', productName: 'Rouge Coco in 432 Cécile', hex: '#C9827C', finish: 'Satin', buyLink: 'https://www.chanel.com' },
  { id: 203, brand: 'Gucci', productName: 'Rouge à Lèvres Satin in 25 Goldie Red', hex: '#C62929', finish: 'Satin', buyLink: 'https://www.gucci.com' },
  { id: 204, brand: 'Armani Beauty', productName: 'Lip Power in 104 Selfless', hex: '#D5A094', finish: 'Satin', buyLink: 'https://www.giorgioarmanibeauty-usa.com' },
  { id: 205, brand: 'Yves Saint Laurent', productName: 'Tatouage Couture in 23 Singular Taupe', hex: '#AD7B70', finish: 'Liquid', buyLink: 'https://www.yslbeautyus.com' },
  { id: 206, brand: 'Givenchy', productName: 'Le Rouge Sheer Velvet in 17 Rouge Érable', hex: '#BC7A6B', finish: 'Matte', buyLink: 'https://www.givenchybeauty.com' },
  { id: 207, brand: 'Shiseido', productName: 'ModernMatte Powder Lipstick in 505 Peep Show', hex: '#E6A59A', finish: 'Matte', buyLink: 'https://www.shiseido.com' },
  { id: 208, brand: 'Lancôme', productName: 'L\'Absolu Rouge in 274 Coeur de Miel', hex: '#C98D80', finish: 'Creme', buyLink: 'https://www.lancome-usa.com' },
  { id: 209, brand: 'Bobbi Brown', productName: 'Luxe Matte Lip Color in Boss Pink', hex: '#D36F7F', finish: 'Matte', buyLink: 'https://www.bobbibrowncosmetics.com' },
  { id: 210, brand: 'Clinique', productName: 'Pop Lip Colour in Nude Pop', hex: '#D9A997', finish: 'Satin', buyLink: 'https://www.clinique.com' },
  { id: 211, brand: 'Buxom', productName: 'Full-On Plumping Lip Cream in White Russian', hex: '#EACDC7', finish: 'Glossy', buyLink: 'https://www.buxomcosmetics.com' },
  { id: 212, brand: 'Tarte', productName: 'Tarteist Quick Dry Matte Lip Paint in Rosé', hex: '#C98980', finish: 'Liquid', buyLink: 'https://tartecosmetics.com' },
  { id: 213, brand: 'Smashbox', productName: 'Always On Liquid Lipstick in Babe Alert', hex: '#C6837C', finish: 'Liquid', buyLink: 'https://www.smashbox.com' },
  { id: 214, brand: 'Stila', productName: 'Stay All Day Liquid Lipstick in Patina', hex: '#B87E81', finish: 'Liquid', buyLink: 'https://www.stilacosmetics.com' },
  { id: 215, brand: 'Morphe', productName: 'Mega Matte Lipstick in Tease', hex: '#A8614F', finish: 'Matte', buyLink: 'https://www.morphe.com' },
  { id: 216, brand: 'BareMinerals', productName: 'Mineralist Hydra-Smoothing Lipstick in Honesty', hex: '#C58C80', finish: 'Satin', buyLink: 'https://www.bareminerals.com' },
  { id: 217, brand: 'Laura Mercier', productName: 'Velour Extreme Matte Lipstick in Vibe', hex: '#B16B66', finish: 'Matte', buyLink: 'https://www.lauramercier.com' },
  { id: 218, brand: 'Kosas', productName: 'Weightless Lip Color in Rosewater', hex: '#DAA0A0', finish: 'Satin', buyLink: 'https://kosas.com' },
  { id: 219, brand: 'Ilia', productName: 'Color Block High Impact Lipstick in Rococo', hex: '#C76A5A', finish: 'Creme', buyLink: 'https://iliabeauty.com' },
  { id: 220, brand: 'Milk Makeup', productName: 'Lip + Cheek in Werk', hex: '#C77E7B', finish: 'Creme', buyLink: 'https://www.milkmakeup.com' },
  { id: 221, brand: 'MAC Cosmetics', productName: 'Powder Kiss Lipstick in Mull It Over', hex: '#D89178', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 222, brand: 'MAC Cosmetics', productName: 'Powder Kiss Lipstick in Devoted to Chili', hex: '#B54932', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 223, brand: 'MAC Cosmetics', productName: 'Lustreglass Sheer-Shine in See Sheer', hex: '#E78778', finish: 'Glossy', buyLink: 'https://www.maccosmetics.com' },
  { id: 224, brand: 'MAC Cosmetics', productName: 'Amplified Lipstick in Blankety', hex: '#E3C1B6', finish: 'Creme', buyLink: 'https://www.maccosmetics.com' },
  { id: 225, brand: 'MAC Cosmetics', productName: 'Satin Lipstick in Faux', hex: '#CC9897', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 226, brand: 'NARS', productName: 'Lipstick in Tolede', hex: '#C6877F', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 227, brand: 'NARS', productName: 'Lipstick in Dolce Vita', hex: '#C4817A', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 228, brand: 'NARS', productName: 'Air Matte Lip Color in Pin Up', hex: '#B7524A', finish: 'Matte', buyLink: 'https://www.narscosmetics.com' },
  { id: 229, brand: 'NARS', productName: 'Afterglow Lip Balm in Orgasm', hex: '#F0B1A8', finish: 'Glossy', buyLink: 'https://www.narscosmetics.com' },
  { id: 230, brand: 'NARS', productName: 'Velvet Lip Glide in Bound', hex: '#C7898B', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 231, brand: 'Charlotte Tilbury', productName: 'K.I.S.S.I.N.G. in Penelope Pink', hex: '#E2AD9B', finish: 'Satin', buyLink: 'https://www.charlottetilbury.com' },
  { id: 232, brand: 'Charlotte Tilbury', productName: 'Matte Revolution in Wedding Belles', hex: '#D8A096', finish: 'Matte', buyLink: 'https://www.charlottetilbury.com' },
  { id: 233, brand: 'Charlotte Tilbury', productName: 'Pillow Talk Diamonds', hex: '#CEA09B', finish: 'Glossy', buyLink: 'https://www.charlottetilbury.com' },
  { id: 234, brand: 'Charlotte Tilbury', productName: 'Hot Lips 2 in In Love With Olivia', hex: '#D88A83', finish: 'Satin', buyLink: 'https://www.charlottetilbury.com' },
  { id: 235, brand: 'Charlotte Tilbury', productName: 'The Super Nudes in Cover Star', hex: '#CE9A86', finish: 'Matte', buyLink: 'https://www.charlottetilbury.com' },
  { id: 236, brand: 'Tom Ford', productName: 'Ultra-Rich Lip Color in Aphrodite', hex: '#D56E74', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 237, brand: 'Tom Ford', productName: 'Lip Color Sheer in Paradiso', hex: '#EE8889', finish: 'Glossy', buyLink: 'https://www.tomford.com' },
  { id: 238, brand: 'Tom Ford', productName: 'Boys & Girls Lip Color in Richard', hex: '#B97970', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 239, brand: 'Tom Ford', productName: 'Lip Spark in Dazed', hex: '#E76B5A', finish: 'Satin', buyLink: 'https://www.tomford.com' },
  { id: 240, brand: 'Tom Ford', productName: 'Soleil Lip Blush', hex: '#E9D6D9', finish: 'Glossy', buyLink: 'https://www.tomford.com' },
  { id: 241, brand: 'Pat McGrath Labs', productName: 'LUST: Gloss in Flesh Fantasy', hex: '#CBA297', finish: 'Glossy', buyLink: 'https://www.patmcgrath.com' },
  { id: 242, brand: 'Pat McGrath Labs', productName: 'LUST: Gloss in Divine Rose', hex: '#C88688', finish: 'Glossy', buyLink: 'https://www.patmcgrath.com' },
  { id: 243, brand: 'Pat McGrath Labs', productName: 'MatteTrance in Christy', hex: '#DDA495', finish: 'Matte', buyLink: 'https://www.patmcgrath.com' },
  { id: 244, brand: 'Pat McGrath Labs', productName: 'Lip Fetish Lip Balm in Clear', hex: '#FCFCFC', finish: 'Glossy', buyLink: 'https://www.patmcgrath.com' },
  { id: 245, brand: 'Pat McGrath Labs', productName: 'Vendetta', hex: '#952B2F', finish: 'Matte', buyLink: 'https://www.patmcgrath.com' },
  { id: 246, brand: 'Fenty Beauty', productName: 'Slip Shine Sheer Shiny Lipstick in Glazed', hex: '#E6A98F', finish: 'Glossy', buyLink: 'https://fentybeauty.com' },
  { id: 247, brand: 'Fenty Beauty', productName: 'Slip Shine Sheer Shiny Lipstick in Retro Rose', hex: '#D18881', finish: 'Glossy', buyLink: 'https://fentybeauty.com' },
  { id: 248, brand: 'Fenty Beauty', productName: 'Poutsicle Hydrating Lip Stain in Mai Type', hex: '#E56D58', finish: 'Liquid', buyLink: 'https://fentybeauty.com' },
  { id: 249, brand: 'Fenty Beauty', productName: 'Stunna Lip Paint in Unlocked', hex: '#E95A97', finish: 'Liquid', buyLink: 'https://fentybeauty.com' },
  { id: 250, brand: 'Fenty Beauty', productName: 'Mattemoiselle in Shawty', hex: '#A15F4C', finish: 'Matte', buyLink: 'https://fentybeauty.com' },
  // And keep going...
  { id: 251, brand: 'Huda Beauty', productName: 'Matte Power Bullet in First Kiss', hex: '#CF917E', finish: 'Matte', buyLink: 'https://hudabeauty.com' },
  { id: 252, brand: 'Huda Beauty', productName: 'Lip Strobe in Angelic', hex: '#EBC1B8', finish: 'Glossy', buyLink: 'https://hudabeauty.com' },
  { id: 253, brand: 'Huda Beauty', productName: '#FauxFilter Lip Shape Pencils in Honey Beige', hex: '#C99882', finish: 'Matte', buyLink: 'https://hudabeauty.com' },
  { id: 254, brand: 'Huda Beauty', productName: 'Liquid Matte in Muse', hex: '#B57C76', finish: 'Liquid', buyLink: 'https://hudabeauty.com' },
  { id: 255, brand: 'Huda Beauty', productName: 'Silk Balm in Blush', hex: '#DAB8B3', finish: 'Glossy', buyLink: 'https://hudabeauty.com' },
  { id: 256, brand: 'Anastasia Beverly Hills', productName: 'Satin Lipstick in Tease', hex: '#D27F6D', finish: 'Satin', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 257, brand: 'Anastasia Beverly Hills', productName: 'Satin Lipstick in Praline', hex: '#B97C61', finish: 'Satin', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 258, brand: 'Anastasia Beverly Hills', productName: 'Lip Gloss in Toffee', hex: '#C18868', finish: 'Glossy', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 259, brand: 'Anastasia Beverly Hills', productName: 'Lip Stain in Rosewood', hex: '#AB6964', finish: 'Liquid', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 260, brand: 'Anastasia Beverly Hills', productName: 'Matte Lipstick in Hush Rose', hex: '#CC938E', finish: 'Matte', buyLink: 'https://www.anastasiabeverlyhills.com' },
  { id: 261, brand: 'Kylie Cosmetics', productName: 'Lip Shine Lacquer in You Are The Sun', hex: '#E79D84', finish: 'Glossy', buyLink: 'https://kyliecosmetics.com' },
  { id: 262, brand: 'Kylie Cosmetics', productName: 'Matte Lip Kit in Angel', hex: '#E3A6A0', finish: 'Liquid', buyLink: 'https://kyliecosmetics.com' },
  { id: 263, brand: 'Kylie Cosmetics', productName: 'High Gloss in Diva', hex: '#D6887A', finish: 'Glossy', buyLink: 'https://kyliecosmetics.com' },
  { id: 264, brand: 'Kylie Cosmetics', productName: 'Koko Kollection in The Bigger The Hoops', hex: '#E2917F', finish: 'Creme', buyLink: 'https://kyliecosmetics.com' },
  { id: 265, brand: 'Kylie Cosmetics', productName: 'Matte Lipstick in Miami', hex: '#ED7A74', finish: 'Matte', buyLink: 'https://kyliecosmetics.com' },
  { id: 266, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Mannequin', hex: '#D6AE9E', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 267, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Rose Matter', hex: '#D9918A', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 268, brand: 'Jeffree Star Cosmetics', productName: 'The Gloss in Shane Glossin\'', hex: '#F9F8F7', finish: 'Glossy', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 269, brand: 'Jeffree Star Cosmetics', productName: 'Velvet Trap in Nude Honey', hex: '#D4A68C', finish: 'Creme', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 270, brand: 'Jeffree Star Cosmetics', productName: 'Velour Liquid Lip in Posh Spice', hex: '#A88E81', finish: 'Liquid', buyLink: 'https://jeffreestarcosmetics.com' },
  { id: 271, brand: 'ColourPop', productName: 'Ultra Glossy Lip in Flying Horses', hex: '#D7A79A', finish: 'Glossy', buyLink: 'https://colourpop.com' },
  { id: 272, brand: 'ColourPop', productName: 'Créme Lux Lipstick in Still Crazy', hex: '#CF8477', finish: 'Creme', buyLink: 'https://colourpop.com' },
  { id: 273, brand: 'ColourPop', productName: 'So Juicy Plumping Gloss in Princess Cut', hex: '#F8F7F6', finish: 'Glossy', buyLink: 'https://colourpop.com' },
  { id: 274, brand: 'ColourPop', productName: 'Blur Lux Lipstick in 21 Questions', hex: '#A15A4C', finish: 'Matte', buyLink: 'https://colourpop.com' },
  { id: 275, brand: 'ColourPop', productName: 'Fresh Kiss Lip Crème in Page Me', hex: '#D38F7F', finish: 'Creme', buyLink: 'https://colourpop.com' },
  { id: 276, brand: 'Maybelline', productName: 'Lifter Gloss in Moon', hex: '#E8D2C9', finish: 'Glossy', buyLink: 'https://www.maybelline.com' },
  { id: 277, brand: 'Maybelline', productName: 'Color Sensational Ultimatte in More Buff', hex: '#D5A68E', finish: 'Matte', buyLink: 'https://www.maybelline.com' },
  { id: 278, brand: 'Maybelline', productName: 'Vivid Hot Lacquer in Charmer', hex: '#C27471', finish: 'Glossy', buyLink: 'https://www.maybelline.com' },
  { id: 279, brand: 'Maybelline', productName: 'SuperStay Ink Crayon in Lead The Way', hex: '#D09289', finish: 'Matte', buyLink: 'https://www.maybelline.com' },
  { id: 280, brand: 'Maybelline', productName: 'Color Sensational in Born With It', hex: '#E4B4B9', finish: 'Creme', buyLink: 'https://www.maybelline.com' },
  { id: 281, brand: 'L\'Oréal Paris', productName: 'Age Perfect Luminous Hydrating Lipstick in Brilliant Brown', hex: '#B57A69', finish: 'Satin', buyLink: 'https://www.lorealparisusa.com' },
  { id: 282, brand: 'L\'Oréal Paris', productName: 'Colour Riche Les Nus in Nu Intense', hex: '#BA7A69', finish: 'Satin', buyLink: 'https://www.lorealparisusa.com' },
  { id: 283, brand: 'L\'Oréal Paris', productName: 'Glow Paradise Balm-in-Lipstick in Nude Heaven', hex: '#E4B7A9', finish: 'Glossy', buyLink: 'https://www.lorealparisusa.com' },
  { id: 284, brand: 'L\'Oréal Paris', productName: 'Infallible Pro-Matte Liquid Lipstick in Nudist', hex: '#CF9988', finish: 'Liquid', buyLink: 'https://www.lorealparisusa.com' },
  { id: 285, brand: 'L\'Oréal Paris', productName: 'Colour Riche in Cinnamon Toast', hex: '#A36852', finish: 'Creme', buyLink: 'https://www.lorealparisusa.com' },
  { id: 286, brand: 'Revlon', productName: 'Colorburst Balm Stain in Honey', hex: '#D6A097', finish: 'Glossy', buyLink: 'https://www.revlon.com' },
  { id: 287, brand: 'Revlon', productName: 'The Luscious Mattes in Shameless', hex: '#B86154', finish: 'Matte', buyLink: 'https://www.revlon.com' },
  { id: 288, brand: 'Revlon', productName: 'Kiss Glow Lip Oil in M-V-P', hex: '#D27F83', finish: 'Glossy', buyLink: 'https://www.revlon.com' },
  { id: 289, brand: 'Revlon', productName: 'Super Lustrous in Teak Rose', hex: '#B6756C', finish: 'Creme', buyLink: 'https://www.revlon.com' },
  { id: 290, brand: 'Revlon', productName: 'PhotoReady Insta-Lip in Nude Attitude', hex: '#D5A998', finish: 'Matte', buyLink: 'https://www.revlon.com' },
  { id: 291, brand: 'Urban Decay', productName: 'Vice Lip Chemistry in Low Key', hex: '#D7A294', finish: 'Glossy', buyLink: 'https://www.urbandecay.com' },
  { id: 292, brand: 'Urban Decay', productName: 'Vice Lipstick in Ravenswood', hex: '#B77573', finish: 'Creme', buyLink: 'https://www.urbandecay.com' },
  { id: 293, brand: 'Urban Decay', productName: 'Stay Naked Vice Lip in Oatmilk', hex: '#D2A99A', finish: 'Satin', buyLink: 'https://www.urbandecay.com' },
  { id: 294, brand: 'Urban Decay', productName: 'Vice Lipstick in Liar', hex: '#B97C78', finish: 'Creme', buyLink: 'https://www.urbandecay.com' },
  { id: 295, brand: 'Urban Decay', productName: '24/7 Glide-On Lip Pencil in Naked2', hex: '#BE9281', finish: 'Matte', buyLink: 'https://www.urbandecay.com' },
  { id: 296, brand: 'Glossier', productName: 'Generation G in Cake', hex: '#E1A98F', finish: 'Matte', buyLink: 'https://www.glossier.com' },
  { id: 297, brand: 'Glossier', productName: 'Ultralip in Villa', hex: '#D3968A', finish: 'Glossy', buyLink: 'https://www.glossier.com' },
  { id: 298, brand: 'Glossier', productName: 'Generation G in Like', hex: '#C693A1', finish: 'Matte', buyLink: 'https://www.glossier.com' },
  { id: 299, brand: 'Glossier', productName: 'Vinylic Lip in Pony', hex: '#A76D5B', finish: 'Glossy', buyLink: 'https://www.glossier.com' },
  { id: 300, brand: 'Glossier', productName: 'Lip Gloss in Red', hex: '#D04E4A', finish: 'Glossy', buyLink: 'https://www.glossier.com' },
  // 200 more
  { id: 301, brand: 'Dior', productName: 'Rouge Dior Forever Liquid in 100 Forever Nude', hex: '#D4A99E', finish: 'Liquid', buyLink: 'https://www.dior.com' },
  { id: 302, brand: 'Chanel', productName: 'Rouge Allure Laque in 63 Ultimate', hex: '#C1837F', finish: 'Liquid', buyLink: 'https://www.chanel.com' },
  { id: 303, brand: 'Gucci', productName: 'Rouge de Beauté Brillant in 214 Call It A Day', hex: '#D28E85', finish: 'Glossy', buyLink: 'https://www.gucci.com' },
  { id: 304, brand: 'Armani Beauty', productName: 'Lip Maestro in 524 Rose-litchi', hex: '#C77A79', finish: 'Liquid', buyLink: 'https://www.giorgioarmanibeauty-usa.com' },
  { id: 305, brand: 'Yves Saint Laurent', productName: 'The Slim Velvet Radical in 28 True Chili', hex: '#B13F32', finish: 'Matte', buyLink: 'https://www.yslbeautyus.com' },
  { id: 306, brand: 'Givenchy', productName: 'Rose Perfecto Lip Balm in 01 Pink Irrésistible', hex: '#F1D1D4', finish: 'Glossy', buyLink: 'https://www.givenchybeauty.com' },
  { id: 307, brand: 'Shiseido', productName: 'TechnoSatin Gel Lipstick in 415 Short Fuse', hex: '#E75841', finish: 'Satin', buyLink: 'https://www.shiseido.com' },
  { id: 308, brand: 'Lancôme', productName: 'Juicy Tubes in Spring Fling', hex: '#E7AAB1', finish: 'Glossy', buyLink: 'https://www.lancome-usa.com' },
  { id: 309, brand: 'Bobbi Brown', productName: 'Extra Lip Tint in Bare Pink', hex: '#EAD7D6', finish: 'Glossy', buyLink: 'https://www.bobbibrowncosmetics.com' },
  { id: 310, brand: 'Clinique', productName: 'Dramatically Different Lipstick in Angel Red', hex: '#D05353', finish: 'Creme', buyLink: 'https://www.clinique.com' },
  { id: 311, brand: 'Buxom', productName: 'Power-full Plump Lip Balm in Dolly Fever', hex: '#CAA4A3', finish: 'Glossy', buyLink: 'https://www.buxomcosmetics.com' },
  { id: 312, brand: 'Tarte', productName: 'SEA Quench Lip Rescue Balm in Nude', hex: '#E4C1B6', finish: 'Glossy', buyLink: 'https://tartecosmetics.com' },
  { id: 313, brand: 'Smashbox', productName: 'Be Legendary Prime & Plush in Stylist', hex: '#D08882', finish: 'Creme', buyLink: 'https://www.smashbox.com' },
  { id: 314, brand: 'Stila', productName: 'Beauty Boss Lip Gloss in Pink Slip', hex: '#E6BCC0', finish: 'Glossy', buyLink: 'https://www.stilacosmetics.com' },
  { id: 315, brand: 'Morphe', productName: 'Lip Crayon in RSVP', hex: '#A86C60', finish: 'Matte', buyLink: 'https://www.morphe.com' },
  { id: 316, brand: 'BareMinerals', productName: 'Gen Nude Matte Liquid in Swag', hex: '#C98D83', finish: 'Liquid', buyLink: 'https://www.bareminerals.com' },
  { id: 317, brand: 'Laura Mercier', productName: 'Rouge Essentiel Silky Crème in Nude Nouveau', hex: '#D6A696', finish: 'Creme', buyLink: 'https://www.lauramercier.com' },
  { id: 318, brand: 'Kosas', productName: 'Wet Lip Oil Gloss in Jellyfish', hex: '#FEFEFE', finish: 'Glossy', buyLink: 'https://kosas.com' },
  { id: 319, brand: 'Ilia', productName: 'Balmy Gloss Tinted Lip Oil in Tahiti', hex: '#D47575', finish: 'Glossy', buyLink: 'https://iliabeauty.com' },
  { id: 320, brand: 'Milk Makeup', productName: 'Electric Glossy Plumper in Pumped', hex: '#FBFBFA', finish: 'Glossy', buyLink: 'https://www.milkmakeup.com' },
  { id: 321, brand: 'MAC Cosmetics', productName: 'Viva Glam I', hex: '#A02D2D', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 322, brand: 'MAC Cosmetics', productName: 'Viva Glam II', hex: '#D2A197', finish: 'Satin', buyLink: 'https://www.maccosmetics.com' },
  { id: 323, brand: 'MAC Cosmetics', productName: 'Viva Glam III', hex: '#874042', finish: 'Matte', buyLink: 'https://www.maccosmetics.com' },
  { id: 324, brand: 'MAC Cosmetics', productName: 'Cremesheen Lipstick in Crème in Your Coffee', hex: '#B57E77', finish: 'Creme', buyLink: 'https://www.maccosmetics.com' },
  { id: 325, brand: 'MAC Cosmetics', productName: 'Retro Matte Liquid in Fashion Legacy', hex: '#E03C2F', finish: 'Liquid', buyLink: 'https://www.maccosmetics.com' },
  { id: 326, brand: 'NARS', productName: 'Powermatte Lipstick in Dragon Girl', hex: '#D03144', finish: 'Matte', buyLink: 'https://www.narscosmetics.com' },
  { id: 327, brand: 'NARS', productName: 'Audacious Lipstick in Jane', hex: '#D18165', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 328, brand: 'NARS', productName: 'Lip Gloss in Chelsea Girls', hex: '#E4BCAF', finish: 'Glossy', buyLink: 'https://www.narscosmetics.com' },
  { id: 329, brand: 'NARS', productName: 'Satin Lip Pencil in Rikugien', hex: '#D19CA0', finish: 'Satin', buyLink: 'https://www.narscosmetics.com' },
  { id: 330, brand: 'NARS', productName: 'Velvet Matte Lip Pencil in Bahama', hex: '#B68270', finish: 'Matte', buyLink: 'https://www.narscosmetics.com' },
  { id: 331, brand: 'Charlotte Tilbury', productName: 'Matte Revolution in Red Carpet Red', hex: '#B1282D', finish: 'Matte', buyLink: 'https://www.charlottetilbury.com' },
  { id: 332, brand: 'Charlotte Tilbury', productName: 'K.I.S.S.I.N.G. in Nude Kate', hex: '#E2B8A3', finish: 'Satin', buyLink: 'https://www.charlottetilbury.com' },
  { id: 333, brand: 'Charlotte Tilbury', productName: 'Lip Lustre in Seduction', hex: '#D3A499', finish: 'Glossy', buyLink: 'https://www.charlottetilbury.com' },
  { id: 334, brand: 'Charlotte Tilbury', productName: 'Hot Lips 2 in Dancefloor Princess', hex: '#E39CA0', finish: 'Satin', buyLink: 'https://www.charlottetilbury.com' },
  { id: 335, brand: 'Charlotte Tilbury', productName: 'Collagen Lip Bath in Peachy Plump', hex: '#E8A793', finish: 'Glossy', buyLink: 'https://www.charlottetilbury.com' },
  { id: 336, brand: 'Tom Ford', productName: 'Lip Color in Nude Vanille', hex: '#E9C7B6', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 337, brand: 'Tom Ford', productName: 'Lip Color Matte in The Perfect Kiss', hex: '#D28980', finish: 'Matte', buyLink: 'https://www.tomford.com' },
  { id: 338, brand: 'Tom Ford', productName: 'Gloss Luxe in Love Lust', hex: '#E19488', finish: 'Glossy', buyLink: 'https://www.tomford.com' },
  { id: 339, brand: 'Tom Ford', productName: 'Lip Color Cream in Impassioned', hex: '#DE5658', finish: 'Creme', buyLink: 'https://www.tomford.com' },
  { id: 340, brand: 'Tom Ford', productName: 'Satin Matte Lip Color in Peche Perfect', hex: '#E7977A', finish: 'Satin', buyLink: 'https://www.tomford.com' },
  { id: 341, brand: 'Pat McGrath Labs', productName: 'BlitzTrance Lipstick in Skinsane', hex: '#D0A18E', finish: 'Satin', buyLink: 'https://www.patmcgrath.com' },
  { id: 342, brand: 'Pat McGrath Labs', productName: 'Lip Fetish Divinyl Lip Shine in Nude Venus', hex: '#D09E90', finish: 'Glossy', buyLink: 'https://www.patmcgrath.com' },
  { id: 343, brand: 'Pat McGrath Labs', productName: 'MatteTrance Lipstick in Guinevere', hex: '#874035', finish: 'Matte', buyLink: 'https://www.patmcgrath.com' },
  { id: 344, brand: 'Pat McGrath Labs', productName: 'LUST: Gloss in Bronze Seduction', hex: '#B77C60', finish: 'Glossy', buyLink: 'https://www.patmcgrath.com' },
  { id: 345, brand: 'Pat McGrath Labs', productName: 'PermaGel Ultra Lip Pencil in Suburbia', hex: '#C57E6D', finish: 'Matte', buyLink: 'https://www.patmcgrath.com' },
  { id: 346, brand: 'Fenty Beauty', productName: 'Cream Glow in Mauve Wives', hex: '#B87B7B', finish: 'Creme', buyLink: 'https://fentybeauty.com' },
  { id: 347, brand: 'Fenty Beauty', productName: 'Icon Velvet Liquid in H.B.I.C.', hex: '#A02D2D', finish: 'Liquid', buyLink: 'https://fentybeauty.com' },
  { id: 348, brand: 'Fenty Beauty', productName: 'Gloss Bomb Heat in Hot Cherry', hex: '#C7414C', finish: 'Glossy', buyLink: 'https://fentybeauty.com' },
  { id: 349, brand: 'Fenty Beauty', productName: 'Slip Shine in Cookies & Cocoa', hex: '#9E6D5B', finish: 'Glossy', buyLink: 'https://fentybeauty.com' },
  { id: 350, brand: 'Fenty Beauty', productName: 'Stunna Lip Paint in Underdawg', hex: '#6E2F32', finish: 'Liquid', buyLink: 'https://fentybeauty.com' },
  // 150 more...
  { id: 351, brand: 'Sephora Collection', productName: 'Rouge Lacquer in Not Your Baby', hex: '#C97E75', finish: 'Satin', buyLink: 'https://www.sephora.com' },
  { id: 352, brand: 'Sephora Collection', productName: '#LIPSTORIES in Brunch Date', hex: '#C48A7D', finish: 'Creme', buyLink: 'https://www.sephora.com' },
  { id: 353, brand: 'Sephora Collection', productName: 'Glossed in Boss', hex: '#E7C8C1', finish: 'Glossy', buyLink: 'https://www.sephora.com' },
  { id: 354, brand: 'Sephora Collection', productName: 'Jelly Melt Glossy Tint in Samba', hex: '#E06B65', finish: 'Glossy', buyLink: 'https://www.sephora.com' },
  { id: 355, brand: 'Sephora Collection', productName: 'Cream Lip Stain in Pink Souffle', hex: '#D29094', finish: 'Liquid', buyLink: 'https://www.sephora.com' },
  { id: 356, brand: 'Rare Beauty', productName: 'Stay Vulnerable Glossy Lip Balm in Nearly Neutral', hex: '#D4A396', finish: 'Glossy', buyLink: 'https://www.rarebeauty.com' },
  { id: 357, brand: 'Rare Beauty', productName: 'Soft Pinch Tinted Lip Oil in Hope', hex: '#D5A09D', finish: 'Glossy', buyLink: 'https://www.rarebeauty.com' },
  { id: 358, brand: 'Rare Beauty', productName: 'Lip Soufflé Matte Lip Cream in Brave', hex: '#B17468', finish: 'Matte', buyLink: 'https://www.rarebeauty.com' },
  { id: 359, brand: 'Rare Beauty', productName: 'Kind Words Matte Lipstick in Humble', hex: '#C7897B', finish: 'Matte', buyLink: 'https://www.rarebeauty.com' },
  { id: 360, brand: 'Rare Beauty', productName: 'With Gratitude Dewy Lip Balm in Thankful', hex: '#C98C81', finish: 'Glossy', buyLink: 'https://www.rarebeauty.com' },
  { id: 361, brand: 'Bite Beauty', productName: 'Power Move Hydrating Soft Matte Lipstick in Sugar Buns', hex: '#D39F8C', finish: 'Matte', buyLink: 'https://www.bitebeauty.com' },
  { id: 362, brand: 'Bite Beauty', productName: 'Agave+ Intensive Vegan Lip Mask in Maple', hex: '#B57C64', finish: 'Glossy', buyLink: 'https://www.bitebeauty.com' },
  { id: 363, brand: 'Bite Beauty', productName: 'Yaysayer Plumping Lip Gloss in Sugar Drizzle', hex: '#E3C1B5', finish: 'Glossy', buyLink: 'https://www.bitebeauty.com' },
  { id: 364, brand: 'Bite Beauty', productName: 'Changemaker Supercharged Micellar Foundation', hex: '#D0A08C', finish: 'Matte', buyLink: 'https://www.bitebeauty.com' },
  { id: 365, brand: 'Bite Beauty', productName: 'Upswing Full-Volume Mascara', hex: '#010101', finish: 'Matte', buyLink: 'https://www.bitebeauty.com' },
  { id: 366, brand: 'Wet n Wild', productName: 'MegaLast High-Shine in Bellini Overflow', hex: '#E7A79A', finish: 'Glossy', buyLink: 'https://www.wetnwildbeauty.com' },
  { id: 367, brand: 'Wet n Wild', productName: 'Cloud Pout Marshmallow Lip Mousse in Girl, You\'re Whipped', hex: '#D09087', finish: 'Matte', buyLink: 'https://www.wetnwildbeauty.com' },
  { id: 368, brand: 'Wet n Wild', productName: 'Mega Slicks Lip Gloss in Rose Gold', hex: '#D9B2A8', finish: 'Glossy', buyLink: 'https://www.wetnwildbeauty.com' },
  { id: 369, brand: 'Wet n Wild', productName: 'MegaLast Matte in Bare It All', hex: '#DBA896', finish: 'Matte', buyLink: 'https://www.wetnwildbeauty.com' },
  { id: 370, brand: 'Wet n Wild', productName: 'Perfect Pout Lip Color in Ring Around the Rosy', hex: '#CA7B85', finish: 'Creme', buyLink: 'https://www.wetnwildbeauty.com' },
  { id: 371, brand: 'NYX', productName: 'Butter Gloss in Crème Brulee', hex: '#E7C0AF', finish: 'Glossy', buyLink: 'https://www.nyxcosmetics.com' },
  { id: 372, brand: 'NYX', productName: 'Soft Matte Lip Cream in London', hex: '#C79A83', finish: 'Matte', buyLink: 'https://www.nyxcosmetics.com' },
  { id: 373, brand: 'NYX', productName: 'This is Milky Gloss in Milk the Coco', hex: '#B58169', finish: 'Glossy', buyLink: 'https://www.nyxcosmetics.com' },
  { id: 374, brand: 'NYX', productName: 'Shine Loud High Shine Lip Color in Goal Getter', hex: '#BC7E6D', finish: 'Liquid', buyLink: 'https://www.nyxcosmetics.com' },
  { id: 375, brand: 'NYX', productName: 'Lip Lingerie XXL in Unlaced', hex: '#C99386', finish: 'Liquid', buyLink: 'https://www.nyxcosmetics.com' },
  { id: 376, brand: 'Melt Cosmetics', productName: 'Ultra-Matte Lipstick in Laced', hex: '#D89F8B', finish: 'Matte', buyLink: 'https://www.meltcosmetics.com' },
  { id: 377, brand: 'Melt Cosmetics', productName: 'Liquid Lipstick in Dreamboy', hex: '#CB806E', finish: 'Liquid', buyLink: 'https://www.meltcosmetics.com' },
  { id: 378, brand: 'Melt Cosmetics', productName: 'Lipstick in Nood', hex: '#D7A88C', finish: 'Matte', buyLink: 'https://www.meltcosmetics.com' },
  { id: 379, brand: 'Melt Cosmetics', productName: 'Digital Dust Duo Blush in Buzz Kill', hex: '#E6856E', finish: 'Matte', buyLink: 'https://www.meltcosmetics.com' },
  { id: 380, brand: 'Melt Cosmetics', productName: 'Metal Gloss in Seance', hex: '#87534D', finish: 'Glossy', buyLink: 'https://www.meltcosmetics.com' },
  { id: 381, brand: 'KVD Beauty', productName: 'Everlasting Hyperlight Liquid Lipstick in Queen of Poisons', hex: '#AD6F6B', finish: 'Liquid', buyLink: 'https://www.kvdveganbeauty.com' },
  { id: 382, brand: 'KVD Beauty', productName: 'Epic Kiss Nourishing Vegan Butter Lipstick in Lolita', hex: '#B2726D', finish: 'Creme', buyLink: 'https://www.kvdveganbeauty.com' },
  { id: 383, brand: 'KVD Beauty', productName: 'Studded Kiss Crème Lipstick in Double Dare', hex: '#C47770', finish: 'Creme', buyLink: 'https://www.kvdveganbeauty.com' },
  { id: 384, brand: 'KVD Beauty', productName: 'XO Lip Gloss in Zine', hex: '#CAB2B0', finish: 'Glossy', buyLink: 'https://www.kvdveganbeauty.com' },
  { id: 385, brand: 'KVD Beauty', productName: 'Everlasting Glimmer Veil in Rocker', hex: '#803B3C', finish: 'Liquid', buyLink: 'https://www.kvdveganbeauty.com' },
  { id: 386, brand: 'Lime Crime', productName: 'Plushies Soft Matte in Butterscotch', hex: '#D7A07E', finish: 'Matte', buyLink: 'https://limecrime.com' },
  { id: 387, brand: 'Lime Crime', productName: 'Wet Cherry Gloss in Naked Cherry', hex: '#EACFCA', finish: 'Glossy', buyLink: 'https://limecrime.com' },
  { id: 388, brand: 'Lime Crime', productName: 'Velvetines in Riot', hex: '#A35A4A', finish: 'Liquid', buyLink: 'https://limecrime.com' },
  { id: 389, brand: 'Lime Crime', productName: 'Soft-Focus Lip Veil in Angelic', hex: '#DFB0A9', finish: 'Creme', buyLink: 'https://limecrime.com' },
  { id: 390, brand: 'Lime Crime', productName: 'Unicorn Lipstick in Birthday Suit', hex: '#D89E8A', finish: 'Creme', buyLink: 'https://limecrime.com' },
  { id: 391, brand: 'Too Faced', productName: 'Lip Injection Extreme Lip Plumper', hex: '#F4E2E0', finish: 'Glossy', buyLink: 'https://www.toofaced.com' },
  { id: 392, brand: 'Too Faced', productName: 'Melted Matte in Sell Out', hex: '#C8877D', finish: 'Liquid', buyLink: 'https://www.toofaced.com' },
  { id: 393, brand: 'Too Faced', productName: 'Peach Puff Long-Wearing Diffused Matte Lip Color in Day Drinking', hex: '#C77D72', finish: 'Matte', buyLink: 'https://www.toofaced.com' },
  { id: 394, brand: 'Too Faced', productName: 'Lady Bold Cream Lipstick in Comeback Queen', hex: '#C48074', finish: 'Creme', buyLink: 'https://www.toofaced.com' },
  { id: 395, brand: 'Too Faced', productName: 'Rich & Dazzling High-Shine Sparkling Lip Gloss in Sunset Crush', hex: '#E7907F', finish: 'Glossy', buyLink: 'https://www.toofaced.com' },
  { id: 396, brand: 'Benefit Cosmetics', productName: 'Benetint', hex: '#D75865', finish: 'Liquid', buyLink: 'https://www.benefitcosmetics.com' },
  { id: 397, brand: 'Benefit Cosmetics', productName: 'California Kissin\' ColorBalm in Nude Pink 521', hex: '#D6A5A0', finish: 'Satin', buyLink: 'https://www.benefitcosmetics.com' },
  { id: 398, brand: 'Benefit Cosmetics', productName: 'Gogo Tint', hex: '#E85B76', finish: 'Liquid', buyLink: 'https://www.benefitcosmetics.com' },
  { id: 399, brand: 'Benefit Cosmetics', productName: 'Punch Pop! Liquid Lip Color in Cherry', hex: '#D44E5D', finish: 'Glossy', buyLink: 'https://www.benefitcosmetics.com' },
  { id: 400, brand: 'Benefit Cosmetics', productName: 'They\'re Real! Double the Lip in Lusty Rose', hex: '#C77E81', finish: 'Satin', buyLink: 'https://www.benefitcosmetics.com' },
  { id: 401, brand: 'Milani', productName: 'Color Fetish Matte Lipstick in Secret', hex: '#C8897A', finish: 'Matte', buyLink: 'https://www.milanicosmetics.com' },
  { id: 402, brand: 'Milani', productName: 'Amore Satin Matte Lip Crème in Lavish', hex: '#B87268', finish: 'Satin', buyLink: 'https://www.milanicosmetics.com' },
  { id: 403, brand: 'Milani', productName: 'Keep It Full Nourishing Lip Plumper in Nude Shimmer', hex: '#E2C3B7', finish: 'Glossy', buyLink: 'https://www.milanicosmetics.com' },
  { id: 404, brand: 'Milani', productName: 'Bold Color Statement Matte Lipstick in I Am Confident', hex: '#B26456', finish: 'Matte', buyLink: 'https://www.milanicosmetics.com' },
  { id: 405, brand: 'Milani', productName: 'Ludicrous Lip Gloss in She\'s A Star', hex: '#D7A79A', finish: 'Glossy', buyLink: 'https://www.milanicosmetics.com' },
  { id: 406, brand: 'Flesh Beauty', productName: 'Fleshy Lips Lipstick in Hungry', hex: '#BA7A6B', finish: 'Satin', buyLink: 'https://www.fleshbeauty.com' },
  { id: 407, brand: 'Flesh Beauty', productName: 'Hot Sauce Lip Gloss in 400', hex: '#E65D4F', finish: 'Glossy', buyLink: 'https://www.fleshbeauty.com' },
  { id: 408, brand: 'Flesh Beauty', productName: 'Strong Flesh Lipstick in Moody', hex: '#9E645A', finish: 'Creme', buyLink: 'https://www.fleshbeauty.com' },
  { id: 409, brand: 'Flesh Beauty', productName: 'Proud Flesh Matte Liquid Lipcolor in Brazen', hex: '#C26955', finish: 'Liquid', buyLink: 'https://www.fleshbeauty.com' },
  { id: 410, brand: 'Flesh Beauty', productName: 'Fleshpot Eye & Cheek Gloss', hex: '#EBD8D2', finish: 'Glossy', buyLink: 'https://www.fleshbeauty.com' },
  { id: 411, brand: 'Covergirl', productName: 'Exhibitionist Cream Lipstick in Sultry Sienna', hex: '#B77363', finish: 'Creme', buyLink: 'https://www.covergirl.com' },
  { id: 412, brand: 'Covergirl', productName: 'Outlast Ultimatte Liquid Lipstick in Sassy-fras', hex: '#C28472', finish: 'Liquid', buyLink: 'https://www.covergirl.com' },
  { id: 413, brand: 'Covergirl', productName: 'Katy Kat Matte in Sphynx', hex: '#E0A898', finish: 'Matte', buyLink: 'https://www.covergirl.com' },
  { id: 414, brand: 'Covergirl', productName: 'Melting Pout Vinyl Vow in Nudist\'s Dream', hex: '#D3A796', finish: 'Glossy', buyLink: 'https://www.covergirl.com' },
  { id: 415, brand: 'Covergirl', productName: 'Colorlicious Lipstick in Romance', hex: '#D26065', finish: 'Creme', buyLink: 'https://www.covergirl.com' },
  { id: 416, brand: 'e.l.f. Cosmetics', productName: 'SRSLY Satin Lipstick in Nectar', hex: '#D89C8A', finish: 'Satin', buyLink: 'https://www.elfcosmetics.com' },
  { id: 417, brand: 'e.l.f. Cosmetics', productName: 'Liquid Matte Lipstick in Tea Rose', hex: '#C98C87', finish: 'Liquid', buyLink: 'https://www.elfcosmetics.com' },
  { id: 418, brand: 'e.l.f. Cosmetics', productName: 'Lip Lacquer in Clear', hex: '#FAFAFA', finish: 'Glossy', buyLink: 'https://www.elfcosmetics.com' },
  { id: 419, brand: 'e.l.f. Cosmetics', productName: 'Hydrating Core Lip Shine in Happy', hex: '#DC8F89', finish: 'Glossy', buyLink: 'https://www.elfcosmetics.com' },
  { id: 420, brand: 'e.l.f. Cosmetics', productName: 'Sheer Slick Lipstick in Golden Pear', hex: '#D2A183', finish: 'Glossy', buyLink: 'https://www.elfcosmetics.com' },
  { id: 421, brand: 'RMS Beauty', productName: 'Lip2Cheek in Demure', hex: '#E0A3A9', finish: 'Creme', buyLink: 'https://www.rmsbeauty.com' },
  { id: 422, brand: 'RMS Beauty', productName: 'Wild With Desire Lipstick in Jezebel', hex: '#B05051', finish: 'Satin', buyLink: 'https://www.rmsbeauty.com' },
  { id: 423, brand: 'RMS Beauty', productName: 'Lip Shine in Bloom', hex: '#D9989F', finish: 'Glossy', buyLink: 'https://www.rmsbeauty.com' },
  { id: 424, brand: 'RMS Beauty', productName: 'Lip2Cheek in Spell', hex: '#D8A99A', finish: 'Creme', buyLink: 'https://www.rmsbeauty.com' },
  { id: 425, brand: 'RMS Beauty', productName: 'Tinted Daily Lip Balm in Peacock Lane', hex: '#D56976', finish: 'Glossy', buyLink: 'https://www.rmsbeauty.com' },
  { id: 426, brand: 'Jouer Cosmetics', productName: 'Long-Wear Lip Crème in Praline', hex: '#C4947C', finish: 'Liquid', buyLink: 'https://www.jouercosmetics.com' },
  { id: 427, brand: 'Jouer Cosmetics', productName: 'High Pigment Lip Gloss in Champs-Élysées', hex: '#D8A095', finish: 'Glossy', buyLink: 'https://www.jouercosmetics.com' },
  { id: 428, brand: 'Jouer Cosmetics', productName: 'Sheer Pigment Lip Gloss in Diamond Walk', hex: '#E7C8BF', finish: 'Glossy', buyLink: 'https://www.jouercosmetics.com' },
  { id: 429, brand: 'Jouer Cosmetics', productName: 'Essential Lip Enhancer Shine Balm', hex: '#F0E0DE', finish: 'Glossy', buyLink: 'https://www.jouercosmetics.com' },
  { id: 430, brand: 'Jouer Cosmetics', productName: 'Long-Wear Lip Topper in Skinny Dip', hex: '#E2C2A7', finish: 'Glossy', buyLink: 'https://www.jouercosmetics.com' },
  { id: 431, brand: 'Ofra Cosmetics', productName: 'Long Lasting Liquid Lipstick in Miami Fever', hex: '#D9734E', finish: 'Liquid', buyLink: 'https://www.ofracosmetics.com' },
  { id: 432, brand: 'Ofra Cosmetics', productName: 'Long Lasting Liquid Lipstick in Pasadena', hex: '#C98A83', finish: 'Liquid', buyLink: 'https://www.ofracosmetics.com' },
  { id: 433, brand: 'Ofra Cosmetics', productName: 'Lip Gloss in Blissful', hex: '#DBB0A5', finish: 'Glossy', buyLink: 'https://www.ofracosmetics.com' },
  { id: 434, brand: 'Ofra Cosmetics', productName: 'Signature Lipstick in Nude', hex: '#D4A48F', finish: 'Creme', buyLink: 'https://www.ofracosmetics.com' },
  { id: 435, brand: 'Ofra Cosmetics', productName: 'Lip Plumper in Pink', hex: '#EAC9C9', finish: 'Glossy', buyLink: 'https://www.ofracosmetics.com' },
  { id: 436, brand: 'Sugar Cosmetics', productName: 'Smudge Me Not Liquid Lipstick in 02 Brink of Pink', hex: '#CF6B8A', finish: 'Liquid', buyLink: 'https://in.sugarcosmetics.com' },
  { id: 437, brand: 'Sugar Cosmetics', productName: 'Matte As Hell Crayon Lipstick in 01 Scarlett O\'Hara', hex: '#C5292D', finish: 'Matte', buyLink: 'https://in.sugarcosmetics.com' },
  { id: 438, brand: 'Sugar Cosmetics', productName: 'Nothing Else Matter Longwear Lipstick in 15 Peach Bunny', hex: '#D7907C', finish: 'Matte', buyLink: 'https://in.sugarcosmetics.com' },
  { id: 439, brand: 'Sugar Cosmetics', productName: 'Time To Shine Lip Gloss in 01 Penelope Peachstop', hex: '#E3A69A', finish: 'Glossy', buyLink: 'https://in.sugarcosmetics.com' },
  { id: 440, brand: 'Sugar Cosmetics', productName: 'Mettle Satin Lipstick in 01 Sophie', hex: '#B26F67', finish: 'Satin', buyLink: 'https://in.sugarcosmetics.com' },
  { id: 441, brand: 'Kay Beauty', productName: 'Matte Lipstick in Snapshot', hex: '#B66F63', finish: 'Matte', buyLink: 'https://www.kaybeauty.in' },
  { id: 442, brand: 'Kay Beauty', productName: 'Creme Lipstick in Red Carpet', hex: '#C23E3E', finish: 'Creme', buyLink: 'https://www.kaybeauty.in' },
  { id: 443, brand: 'Kay Beauty', productName: 'Lip Crayon in Rom-Com', hex: '#CE8B80', finish: 'Matte', buyLink: 'https://www.kaybeauty.in' },
  { id: 444, brand: 'Kay Beauty', productName: 'Gloss in Paparazzi', hex: '#D9AFAC', finish: 'Glossy', buyLink: 'https://www.kaybeauty.in' },
  { id: 445, brand: 'Kay Beauty', productName: 'Matteinee Lipstick in On-Screen', hex: '#B87A71', finish: 'Matte', buyLink: 'https://www.kaybeauty.in' },
  { id: 446, brand: 'Lakmé', productName: 'Absolute Matte Melt Liquid Lip Color in Mild Mauve', hex: '#B98182', finish: 'Liquid', buyLink: 'https://www.lakmeindia.com' },
  { id: 447, brand: 'Lakmé', productName: '9 to 5 Primer + Matte Lip Color in Red Coat', hex: '#BD3339', finish: 'Matte', buyLink: 'https://www.lakmeindia.com' },
  { id: 448, brand: 'Lakmé', productName: 'Enrich Lip Crayon in Peach Magnet', hex: '#E29E87', finish: 'Creme', buyLink: 'https://www.lakmeindia.com' },
  { id: 449, brand: 'Lakmé', productName: 'Absolute Spotlight Lip Gloss in Copper Light', hex: '#C88E75', finish: 'Glossy', buyLink: 'https://www.lakmeindia.com' },
  { id: 450, brand: 'Lakmé', productName: 'Cushion Matte Lipstick in Pink Blush', hex: '#D48A96', finish: 'Matte', buyLink: 'https://www.lakmeindia.com' },
  { id: 451, brand: 'Flower Beauty', productName: 'Petal Pout Lip Color in Naked Blush', hex: '#D5A098', finish: 'Creme', buyLink: 'https://www.flowerbeauty.com' },
  { id: 452, brand: 'Flower Beauty', productName: 'Miracle Matte Liquid Lip in Nude Blush', hex: '#C99186', finish: 'Liquid', buyLink: 'https://www.flowerbeauty.com' },
  { id: 453, brand: 'Flower Beauty', productName: 'Perfect Pout Moisturizing Lipstick in Spiced Petal', hex: '#B8726A', finish: 'Creme', buyLink: 'https://www.flowerbeauty.com' },
  { id: 454, brand: 'Flower Beauty', productName: 'Galaxy Glaze Lip Gloss in Opalescence', hex: '#E7D5D9', finish: 'Glossy', buyLink: 'https://www.flowerbeauty.com' },
  { id: 455, brand: 'Flower Beauty', productName: 'Bitten Lip Stain in Play', hex: '#D0676F', finish: 'Liquid', buyLink: 'https://www.flowerbeauty.com' },
  { id: 456, brand: 'Physicians Formula', productName: 'The Healthy Lip Velvet Liquid Lipstick in Tu-lip Treatment', hex: '#C46F72', finish: 'Liquid', buyLink: 'https://www.physiciansformula.com' },
  { id: 457, brand: 'Physicians Formula', productName: 'Organic Wear Tinted Lip Treatment in Tickled Pink', hex: '#E1AAB0', finish: 'Glossy', buyLink: 'https://www.physiciansformula.com' },
  { id: 458, brand: 'Physicians Formula', productName: 'Rosé All Day Velvet Lip Color in First-Class', hex: '#B87872', finish: 'Satin', buyLink: 'https://www.physiciansformula.com' },
  { id: 459, brand: 'Physicians Formula', productName: 'Murumuru Butter Lip Cream in Brazilian Nut', hex: '#B77F6A', finish: 'Creme', buyLink: 'https://www.physiciansformula.com' },
  { id: 460, brand: 'Physicians Formula', productName: 'Diamond Lip Plumper in Light Pink Princess Cut', hex: '#EACFD1', finish: 'Glossy', buyLink: 'https://www.physiciansformula.com' },
  { id: 461, brand: 'Beauty Bakerie', productName: 'Matte Lip Whip in Honey', hex: '#D3A38A', finish: 'Liquid', buyLink: 'https://www.beautybakerie.com' },
  { id: 462, brand: 'Beauty Bakerie', productName: 'Lip Gloss in Enchanted Jelly', hex: '#CE7878', finish: 'Glossy', buyLink: 'https://www.beautybakerie.com' },
  { id: 463, brand: 'Beauty Bakerie', productName: 'Cake Pop Lippie in Cherry Bomb', hex: '#C03740', finish: 'Satin', buyLink: 'https://www.beautybakerie.com' },
  { id: 464, brand: 'Beauty Bakerie', productName: 'Sugar Sticks Lip Liner in Chocolate Therapy', hex: '#875B4B', finish: 'Matte', buyLink: 'https://www.beautybakerie.com' },
  { id: 465, brand: 'Beauty Bakerie', productName: 'The Jellies Lip Jelly in Donut Glaze', hex: '#F0E5E0', finish: 'Glossy', buyLink: 'https://www.beautybakerie.com' },
  { id: 466, brand: 'Uoma Beauty', productName: 'Badass Icon Matte Lipstick in Angela', hex: '#C1846D', finish: 'Matte', buyLink: 'https://uomabeauty.com' },
  { id: 467, brand: 'Uoma Beauty', productName: 'Boss Gloss Liquid Marble in Class', hex: '#D1A396', finish: 'Glossy', buyLink: 'https://uomabeauty.com' },
  { id: 468, brand: 'Uoma Beauty', productName: 'Badass MF Lip Liner in Angelou', hex: '#A86D58', finish: 'Matte', buyLink: 'https://uomabeauty.com' },
  { id: 469, brand: 'Uoma Beauty', productName: 'Black Magic Hypnotic Impact High Shine Lipstick in Poise', hex: '#C67A6C', finish: 'Satin', buyLink: 'https://uomabeauty.com' },
  { id: 470, brand: 'Uoma Beauty', productName: 'Badass MF Lip Liner in Simone', hex: '#804537', finish: 'Matte', buyLink: 'https://uomabeauty.com' },
  { id: 471, brand: 'Juvia\'s Place', productName: 'The Nude Velvety Matte Lipstick in Me', hex: '#DAB3A1', finish: 'Matte', buyLink: 'https://www.juviasplace.com' },
  { id: 472, brand: 'Juvia\'s Place', productName: 'The Reds & Berries Liquid Lipstick in So Red', hex: '#BC242A', finish: 'Liquid', buyLink: 'https://www.juviasplace.com' },
  { id: 473, brand: 'Juvia\'s Place', productName: 'Glass Gloss in It\'s All Me', hex: '#E5C1B2', finish: 'Glossy', buyLink: 'https://www.juviasplace.com' },
  { id: 474, brand: 'Juvia\'s Place', productName: 'Luxe Lip Liner in Sweet Nothing', hex: '#B57E70', finish: 'Matte', buyLink: 'https://www.juviasplace.com' },
  { id: 475, brand: 'Juvia\'s Place', productName: 'The Nude Gloss in Sis!', hex: '#C49681', finish: 'Glossy', buyLink: 'https://www.juviasplace.com' },
  { id: 476, brand: 'Tower 28 Beauty', productName: 'ShineOn Lip Jelly in Cashew', hex: '#D4A396', finish: 'Glossy', buyLink: 'https://www.tower28beauty.com' },
  { id: 477, brand: 'Tower 28 Beauty', productName: 'ShineOn Milky Lip Jelly in Coconut', hex: '#D8B8B2', finish: 'Glossy', buyLink: 'https://www.tower28beauty.com' },
  { id: 478, brand: 'Tower 28 Beauty', productName: 'JuiceBalm Tinted Lip Balm in Mix', hex: '#D28680', finish: 'Glossy', buyLink: 'https://www.tower28beauty.com' },
  { id: 479, brand: 'Tower 28 Beauty', productName: 'Lip & Cheek Cream Blush in Power Hour', hex: '#D87A6A', finish: 'Creme', buyLink: 'https://www.tower28beauty.com' },
  { id: 480, brand: 'Tower 28 Beauty', productName: 'OneLiner Multi-Liner in Work of Art', hex: '#B87262', finish: 'Matte', buyLink: 'https://www.tower28beauty.com' },
  { id: 481, brand: 'Merit', productName: 'Signature Lip in Slip', hex: '#D2A396', finish: 'Satin', buyLink: 'https://www.meritbeauty.com' },
  { id: 482, brand: 'Merit', productName: 'Shade Slick in Au Naturel', hex: '#E4C1B6', finish: 'Glossy', buyLink: 'https://www.meritbeauty.com' },
  { id: 483, brand: 'Merit', productName: 'Flush Balm in Cheeky', hex: '#D48680', finish: 'Creme', buyLink: 'https://www.meritbeauty.com' },
  { id: 484, brand: 'Merit', productName: 'Signature Lip in L\'Avenue', hex: '#A8645D', finish: 'Satin', buyLink: 'https://www.meritbeauty.com' },
  { id: 485, brand: 'Merit', productName: 'Shade Slick in Taupe', hex: '#BE9583', finish: 'Glossy', buyLink: 'https://www.meritbeauty.com' },
  { id: 486, brand: 'Victoria Beckham Beauty', productName: 'Posh Lipstick in Spice', hex: '#B97E6D', finish: 'Satin', buyLink: 'https://victoriabeckhambeauty.com' },
  { id: 487, brand: 'Victoria Beckham Beauty', productName: 'Bitten Lip Tint in Chérie', hex: '#D1817F', finish: 'Liquid', buyLink: 'https://victoriabeckhambeauty.com' },
  { id: 488, brand: 'Victoria Beckham Beauty', productName: 'Lip Definer in 02', hex: '#C28B7A', finish: 'Matte', buyLink: 'https://victoriabeckhambeauty.com' },
  { id: 489, brand: 'Victoria Beckham Beauty', productName: 'Posh Gloss in Poolside', hex: '#E7B6AB', finish: 'Glossy', buyLink: 'https://victoriabeckhambeauty.com' },
  { id: 490, brand: 'Victoria Beckham Beauty', productName: 'Posh Lipstick in Girl', hex: '#CE9A86', finish: 'Satin', buyLink: 'https://victoriabeckhambeauty.com' },
  { id: 491, brand: 'Westman Atelier', productName: 'Lip Suede in Les Rouges', hex: '#A84C4C', finish: 'Matte', buyLink: 'https://www.westman-atelier.com' },
  { id: 492, brand: 'Westman Atelier', productName: 'Squeaky Clean Liquid Lip Balm in Nana', hex: '#D8998D', finish: 'Glossy', buyLink: 'https://www.westman-atelier.com' },
  { id: 493, brand: 'Westman Atelier', productName: 'Baby Cheeks Blush Stick in Petal', hex: '#D9A1A0', finish: 'Creme', buyLink: 'https://www.westman-atelier.com' },
  { id: 494, brand: 'Westman Atelier', productName: 'Lip Suede in Les Nudes', hex: '#C79A8B', finish: 'Matte', buyLink: 'https://www.westman-atelier.com' },
  { id: 495, brand: 'Westman Atelier', productName: 'Squeaky Clean Liquid Lip Balm in Garçonne', hex: '#C46F65', finish: 'Glossy', buyLink: 'https://www.westman-atelier.com' },
  { id: 496, brand: 'Hermès', productName: 'Rouge Hermès, Matte lipstick in 64 Rouge Casaque', hex: '#C82D36', finish: 'Matte', buyLink: 'https://www.hermes.com' },
  { id: 497, brand: 'Hermès', productName: 'Rouge Hermès, Satin lipstick in 18 Rose Encens', hex: '#D1A09B', finish: 'Satin', buyLink: 'https://www.hermes.com' },
  { id: 498, brand: 'Hermès', productName: 'Hermèsistible Infused Lip Care Oil in 03 Rose Pitaya', hex: '#E38592', finish: 'Glossy', buyLink: 'https://www.hermes.com' },
  { id: 499, brand: 'Hermès', productName: 'Poppy Lip Shine', hex: '#E76C5C', finish: 'Glossy', buyLink: 'https://www.hermes.com' },
  { id: 500, brand: 'Hermès', productName: 'Rouge Hermès, Satin lipstick in 33 Orange Boîte', hex: '#E76B3C', finish: 'Satin', buyLink: 'https://www.hermes.com' },
  { id: 501, brand: 'Lisa Eldridge', productName: 'Luxuriously Lucent Lip Colour in Kitten Mischief', hex: '#E0988A', finish: 'Satin', buyLink: 'https://www.lisaeldridge.com' },
  { id: 502, brand: 'Lisa Eldridge', productName: 'True Velvet Lip Colour in Velvet Morning', hex: '#EC613D', finish: 'Matte', buyLink: 'https://www.lisaeldridge.com' },
  { id: 503, brand: 'Lisa Eldridge', productName: 'Gloss Embrace Lip Gloss in Affair', hex: '#D2827B', finish: 'Glossy', buyLink: 'https://www.lisaeldridge.com' },
  { id: 504, brand: 'Lisa Eldridge', productName: 'Insanely Saturated Lip Colour in Skyscraper Rose', hex: '#E04E7B', finish: 'Creme', buyLink: 'https://www.lisaeldridge.com' },
  { id: 505, brand: 'Lisa Eldridge', productName: 'True Velvet Lip Colour in Velvet Ribbon', hex: '#B73133', finish: 'Matte', buyLink: 'https://www.lisaeldridge.com' }
];


// Helper function to calculate color difference (CIE76 algorithm)
// This is a simplified version for demonstration purposes.
function getColorDifference(hex1: string, hex2: string): number {
  const rgb1 = hexToRgb(hex1);
  const rgb2 = hexToRgb(hex2);

  if (!rgb1 || !rgb2) return Infinity;

  // Using simple Euclidean distance for RGB values
  const deltaR = rgb1.r - rgb2.r;
  const deltaG = rgb1.g - rgb2.g;
  const deltaB = rgb1.b - rgb2.b;

  return Math.sqrt(deltaR * deltaR + deltaG * deltaG + deltaB * deltaB);
}

function hexToRgb(hex: string): { r: number, g: number, b: number } | null {
  const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
  return result ? {
    r: parseInt(result[1], 16),
    g: parseInt(result[2], 16),
    b: parseInt(result[3], 16),
  } : null;
}

/**
 * Finds the most similar lipstick products from the database based on a hex color.
 * @param targetHex The hex color to match against.
 * @returns An array of the top 3 similar lipstick products.
 */
export async function findSimilarLipsticks(targetHex: string): Promise<LipstickProduct[]> {
  if (!targetHex) return [];

  const productsWithDifference = lipstickDatabase.map(product => ({
    ...product,
    difference: getColorDifference(targetHex, product.hex),
  }));

  // Sort by color difference (ascending)
  productsWithDifference.sort((a, b) => a.difference - b.difference);
  
  // Return the top 3 matches
  return productsWithDifference.slice(0, 3);
}
